services:
  - type: web
    name: fitness-bot
    runtime: python
    buildCommand: ""
    startCommand: python3 main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
